### ISSUE TITLE
Signs go black randomly

### ISSUE THREAD

**Issue by francistheodorecatte** [phineasthecat/signage_script#6]
Seems worse as of the latest commit 5929c47acec354bf81fefee5a253bb6b8bb902b3, where I added a random reboot (untested) to try and fix the problem. Now they go blank within minutes/hours.

Little bit of background:
Basically every couple of days or weeks, the Pi's display output will go blank. Not sure if this is an upstream issue or something my script causes. Will do some more investigation and get the random reboot script working properly.

This has been happening since this script was first rolled out en masse; when I had early revisions of the script (circa December 2016) running on a single testing Pi, it was perfectly stable for over a week without issues.

In any case, as of right now, commit c3731e2bb3dcb1489b846aca36eb85236aa266c7 is the most stable, but signs still go blank and require hard resetting every couple of days/weeks. You can get around this by manually setting the crontab script provided in this repository (until I fix the automatic creation of the crontab rule).

**Comment by francistheodorecatte** [comment]
Looks to be a problem with terminal blanking and powersave features? Going to push some stuff to testing, and then try it out in production for a while to see if that solves the problem.

Basically adding `sh -c 'setterm -blank 0 -powersave off -powerdown 0 < /dev/console > /dev/console 2>&1'` to `/etc/rc.local`, setting rc.local to executable, and issuing a reboot.

Also going to add `dispmanx_offline=1` and `config_hdmi_boost=4` to `/boot/config.txt` just in case it's a problem with cheap HDMI cables (possible in this use case... the boss loves monoprice.)

Will update soon and push the new features intended to combat this to the master branch if all goes well. :)

**Comment by francistheodorecatte** [comment]
Oh and as of this next commit, no untested code will go to master. You'll be able to update with impunity.

Took me long enough, eh?

**Comment by francistheodorecatte** [comment]
Pushed an update (c1394f1c55dde73b86ac46e78dba9db8d6ced785) to testing. Deploying it now to see how it fares.

**Comment by phineasthecat** [comment]
So it turned out you need to disable the terminal screen blanking and power saving which you can do by putting the following into /etc/bash.bashrc:
setterm -blank 0
setterm -powerdown 0
